services:
  recorder:
    image: bililive/recorder
    ports:
      - "2356:2356"
    volumes:
      - ./rec:/rec
    command: [
      "run", 
      "--bind", 
      "http://*:2356", 
      "--http-basic-user", 
      "${RECORDER_USER}", 
      "--http-basic-pass",
      "${RECORDER_PASS}",
      "/rec"
    ]